//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orvos
{
    using System;
    using System.Collections.Generic;
    
    public partial class kezeles
    {
        public int kezeles_id { get; set; }
        public Nullable<int> paciens_id { get; set; }
        public Nullable<int> orvos_id { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
        public Nullable<int> kezdesido { get; set; }
        public Nullable<int> idotartam { get; set; }
        public string megjegyzes { get; set; }
    
        public virtual orvos orvos { get; set; }
        public virtual paciens paciens { get; set; }
    }
}
