//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orvos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class klinikaEntities : DbContext
    {
        public klinikaEntities()
            : base("name=klinikaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<kezeles> kezeles { get; set; }
        public virtual DbSet<orvos> orvos { get; set; }
        public virtual DbSet<paciens> paciens { get; set; }
        public virtual DbSet<szakterulet> szakterulet { get; set; }
    }
}
