//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orvos
{
    using System;
    using System.Collections.Generic;
    
    public partial class paciens
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public paciens()
        {
            this.kezeles = new HashSet<kezeles>();
        }
    
        public int paciens_id { get; set; }
        public string nev { get; set; }
        public Nullable<System.DateTime> szuletett { get; set; }
        public string telefon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kezeles> kezeles { get; set; }
    }
}
